### ISSUE TITLE
正在拜读代码，不过我把您的代码copy到我的小程序中发现，每个滚筒的奖项图片全都定位重叠到一起了，找了半天没找到原因

### ISSUE THREAD

**Issue by kubixiaoguo** [zpzxgcr/choujiang#1]
![_20181106180104](https://user-images.githubusercontent.com/29883509/48057024-fe9cfc80-e1ed-11e8-9cdc-5fa60895d977.png)

请问为什么会这样呢

**Comment by zpzxgcr** [comment]
你选择元素看一下定位的位置是否乱了

**Comment by kubixiaoguo** [comment]
这个我找到原因了，是小程序基础库的原因。在1.9.91以下的版本translateZ不起作用，我一般是用1.9.4的版本来开发的。小程序官方文档了我找了，也没说translateZ哪个版本开始支持。
